### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by dahlek** [emolter/pylanetary#32]
Hi Ned, I was trying to install pylanetary and got the following error when running $ pip install -r requirements.txt

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

Is the problem on my end? If so maybe we should add some more explicit instructions to help future folks know for sure what to do.

**Comment by emolter** [comment]
The instructions currently say:

Installation
To install, download the requirements.txt file and then run (tested in a blank Conda environment):

```
conda create -n pylanetary-tester python=3.9
conda activate pylanetary-tester
pip install -r requirements.txt
pip install git+https://github.com/emolter/pylanetary.git@main
```

So your problem is that you didn't download requirements.txt.  But I see why the problem happened, it's because my eyes (and I assume yours too) anticipated all the instructions to be in the code block.  I will instead make this a bulleted list and hopefully that improves things

**Comment by emolter** [comment]
let me know if [this looks better](https://pylanetary.readthedocs.io/en/latest/installation.html), and whether this solved your problem or not

**Comment by dahlek** [comment]
Great, got it. It might help to explicitly say you can just save it in your home directory?

**Comment by emolter** [comment]
did you get the install to work? if so I will close the issue

**Comment by dahlek** [comment]
Yeah it worked!


Emma Dahl, PhD
NASA Postdoctoral Fellow
Jet Propulsion Laboratory
***@***.***
***@***.*** (personal email)
jpl.webex.com/meet/emmadahl
(she/her)



From: Ned Molter ***@***.***>
Date: Thursday, August 10, 2023 at 3:29 PM
To: emolter/pylanetary ***@***.***>
Cc: Dahl, Emma K (US 3222-Affiliate) ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [emolter/pylanetary] install error (Issue #32)

did you get the install to work? if so I will close the issue
